# Generated by Django 3.2.7 on 2023-07-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('passport_no', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('type_of_client', models.CharField(max_length=200)),
                ('number_of_client', models.CharField(max_length=200)),
                ('status_of_client', models.CharField(max_length=200)),
                ('type_of_tour_trip', models.CharField(max_length=200)),
                ('holiday_idea', models.CharField(max_length=200)),
                ('client_Age_group', models.CharField(max_length=200)),
                ('include_in_tour', models.CharField(max_length=200)),
                ('exclude_in_tour', models.CharField(max_length=200)),
                ('meeting_point', models.CharField(max_length=200)),
                ('language', models.EmailField(max_length=200)),
                ('time_confirmation', models.DateTimeField(max_length=200)),
                ('tour_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.toursite')),
            ],
        ),
    ]
