# Generated by Django 3.2.7 on 2023-07-09 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('acc_name', models.CharField(max_length=200)),
                ('acc_no', models.CharField(max_length=200)),
                ('privacy_policy', models.TextField()),
                ('terms_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testmonial/')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('guider_image', models.ImageField(blank=True, null=True, upload_to='guider/')),
            ],
        ),
        migrations.CreateModel(
            name='TourSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('tour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.toursite')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('maritalstatus', models.CharField(max_length=200)),
                ('no_of_client', models.IntegerField()),
                ('status_of_client', models.CharField(max_length=200)),
                ('type_of_client', models.CharField(max_length=200)),
                ('type_of_tour_trip', models.CharField(max_length=200)),
                ('holiday_idea', models.CharField(max_length=200)),
                ('client_age_group', models.CharField(max_length=200)),
                ('include_in_tour', models.CharField(max_length=200)),
                ('exclude_in_tour', models.CharField(max_length=200)),
                ('meeting_point', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('passport_no', models.CharField(max_length=200)),
                ('time_confirmation', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.toursite')),
            ],
        ),
    ]
