# Generated by Django 3.2.7 on 2023-07-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_confirmation',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour_program',
        ),
    ]
