# Generated by Django 3.2.7 on 2023-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opener',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
