# Generated by Django 3.2.7 on 2023-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_opener_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueSafari_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('privacy_policy', models.TextField(max_length=800)),
                ('terms_condition', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HalfDay_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Island_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tour_guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zanzibar_shallow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zanzibar_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('people_amount', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=200)),
            ],
        ),
    ]
