# Generated by Django 3.2.7 on 2023-07-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_toursite_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_image',
        ),
        migrations.RemoveField(
            model_name='tour_guides',
            name='guider_image',
        ),
    ]
