# Generated by Django 3.2.7 on 2023-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230720_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opener',
            name='description',
        ),
        migrations.AddField(
            model_name='opener',
            name='description2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opener',
            name='discription',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
