# Generated by Django 3.2.7 on 2023-07-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_aboutus_whatsapp_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toursite',
            name='created_by',
        ),
    ]
