# Generated by Django 3.2.7 on 2023-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_toursite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_site/'),
        ),
    ]
