# Generated by Django 3.2.7 on 2023-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_toursite_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toursite',
            old_name='discriptions',
            new_name='tour_type',
        ),
        migrations.RemoveField(
            model_name='toursite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toursite',
            name='location',
        ),
        migrations.RemoveField(
            model_name='toursite',
            name='people_amount',
        ),
    ]
