# Generated by Django 3.2.7 on 2023-07-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230721_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Half_day_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tour_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='tour_name',
        ),
        migrations.RenameModel(
            old_name='TourSite',
            new_name='Full_day_tour',
        ),
        migrations.CreateModel(
            name='Booking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('maritalstatus', models.CharField(max_length=200)),
                ('no_of_client', models.IntegerField()),
                ('status_of_client', models.CharField(max_length=200)),
                ('type_of_client', models.CharField(max_length=200)),
                ('type_of_tour_trip', models.CharField(max_length=200)),
                ('holiday_idea', models.CharField(max_length=200)),
                ('client_age_group', models.CharField(max_length=200)),
                ('include_in_tour', models.CharField(max_length=200)),
                ('exclude_in_tour', models.CharField(max_length=200)),
                ('meeting_point', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('passport_no', models.CharField(max_length=200)),
                ('time_confirmation', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tour_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.full_day_tour')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.half_day_tour'),
        ),
    ]
