# Generated by Django 3.2.7 on 2023-07-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230721_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_day_tour',
            name='tour_type',
        ),
        migrations.RemoveField(
            model_name='half_day_tour',
            name='tour_type',
        ),
    ]
