# Generated by Django 3.2.7 on 2023-07-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230721_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday_Leisure_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('maritalstatus', models.CharField(max_length=200)),
                ('no_of_client', models.IntegerField()),
                ('status_of_client', models.CharField(max_length=200)),
                ('type_of_client', models.CharField(max_length=200)),
                ('type_of_tour_trip', models.CharField(max_length=200)),
                ('holiday_idea', models.CharField(max_length=200)),
                ('client_age_group', models.CharField(max_length=200)),
                ('include_in_tour', models.CharField(max_length=200)),
                ('exclude_in_tour', models.CharField(max_length=200)),
                ('meeting_point', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('passport_no', models.CharField(max_length=200)),
                ('time_confirmation', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tour_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.holiday_leisure_study')),
            ],
        ),
    ]
