# Generated by Django 3.2.7 on 2023-07-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_booking3_holiday_leisure_study'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking2',
            new_name='Full_Day_Booking',
        ),
        migrations.RenameModel(
            old_name='Booking3',
            new_name='Half_Day_Booking',
        ),
        migrations.RenameModel(
            old_name='Booking',
            new_name='Holiday_Ideas_Booking',
        ),
        migrations.RenameModel(
            old_name='Tour_guides',
            new_name='Tour_guider',
        ),
        migrations.AlterField(
            model_name='half_day_booking',
            name='tour_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.half_day_tour'),
        ),
        migrations.AlterField(
            model_name='holiday_ideas_booking',
            name='tour_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.holiday_leisure_study'),
        ),
    ]
