# Generated by Django 3.2.7 on 2023-07-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_day_booking',
            name='type_of_tour_trip',
        ),
        migrations.RemoveField(
            model_name='half_day_booking',
            name='type_of_tour_trip',
        ),
        migrations.RemoveField(
            model_name='holiday_ideas_booking',
            name='type_of_tour_trip',
        ),
    ]
